In [1]:
%matplotlib inline

import pandas as pd
import numpy as np

pd.set_option('max_columns', 100)

In [ ]:
{u→0, g→1, r→2, i→3, z→4, y→5}

In [2]:
df_train = pd.read_csv('training_set.csv', sep = ',', header = 0, dtype = {'passband': np.object})
df_train.passband = 'passband_'+ df_train.passband
df_train.passband = df_train.passband.astype('category')
print (df_train.shape)
df_train.dtypes

(1421705, 6)

object_id       int64
mjd           float64
passband     category
flux          float64
flux_err      float64
detected        int64
dtype: object

In [3]:
df_train.head()

   object_id         mjd    passband        flux   flux_err  detected
0        615  59750.4229  passband_2 -544.810303   3.622952         1
1        615  59750.4306  passband_1 -816.434326   5.553370         1
2        615  59750.4383  passband_3 -471.385529   3.801213         1
3        615  59750.4450  passband_4 -388.984985  11.395031         1
4        615  59752.4070  passband_2 -681.858887   4.041204         1

In [4]:
df_temp = df_train.groupby(['object_id', 'passband']).flux.agg({'min', 'max', 'mean', 'std', 'skew'})
df_temp = df_temp[['min', 'max', 'mean', 'std', 'skew']]
df_temp.reset_index(level = 1, drop = False, inplace = True)
df_temp['flux_range'] = df_temp['max'] - df_temp['min']
df_temp['flux_rel_range'] = df_temp['flux_range']/df_temp['mean']
df_temp.head()

,passband,min,max,mean,std,skew,flux_range,flux_rel_range
object_id,,,,,,,,
615,passband_0,-116.913223,125.182808,-3.254554,83.944735,0.128917,242.096031,-74.386845
615,passband_1,-1100.440063,660.626343,-385.699911,601.787302,0.415580,1761.066406,-4.565898
615,passband_2,-681.858887,611.984558,-134.146566,455.121346,0.339918,1293.843445,-9.644999
615,passband_3,-530.644592,445.737061,-121.103501,335.425053,0.293128,976.381653,-8.062373
615,passband_4,-422.184509,381.953735,-55.954592,291.803449,0.200096,804.138244,-14.371264

In [5]:
df_grouped = df_temp.pivot(columns = 'passband')
df_grouped.head()

                  min                                                   \
passband   passband_0   passband_1  passband_2  passband_3  passband_4
object_id
615       -116.913223 -1100.440063 -681.858887 -530.644592 -422.184509
713        -14.735178   -11.715749  -10.067919  -12.394593  -12.286801
730         -3.459960    -3.393080   -2.848838   -5.435799   -5.836310
745         -3.874349    -3.618410   -2.159753   -4.944036  -15.494463
1124        -6.804703    -2.622109   -2.084535   -2.800270  -16.543753

                              max                                      \
passband   passband_5  passband_0  passband_1  passband_2  passband_3
object_id
615       -422.815094  125.182808  660.626343  611.984558  445.737061
713        -14.211164   14.509829    9.129021   10.529041   11.330316
730        -19.159811    5.942166    5.693109   20.994711   33.572102
745        -10.249387   18.014029  192.244293  220.795212  203.250702
1124       -10.860540    5.330927   37.170177  106.671692  139.818405

                                        mean                          \
passband   passband_4  passband_5 passband_0  passband_1  passband_2
object_id
615        381.953735  378.188141  -3.254554 -385.699911 -134.146566
713          9.827934   14.770886  -2.720398   -1.019804   -0.794238
730         41.159981   47.310059  -0.048080    0.141057    2.400870
745        183.633118  141.513290   1.797523    5.717394    9.711532
1124       143.600189  109.157585   0.660948    4.634637   10.243968

                                                   std              \
passband   passband_3 passband_4 passband_5 passband_0  passband_1
object_id
615       -121.103501 -55.954592 -47.449847  83.944735  601.787302
713         -0.986966  -0.900262  -1.794175   7.113509    5.712334
730          3.236164   4.308728   4.539396   1.828872    1.807229
745         14.412924  13.134436  10.746138   4.374445   25.964659
1124        11.086555   9.906102   6.896742   2.360084    8.107525

                                                                skew  \
passband   passband_2  passband_3  passband_4  passband_5 passband_0
object_id
615        455.121346  335.425053  291.803449  294.779522   0.128917
713          5.770738    6.450413    6.406989    7.094073   0.260052
730          5.559483    8.191987   10.710344   13.332758   0.356910
745         31.957997   34.967698   33.069053   26.060130   2.023211
1124        21.319854   26.270649   26.865913   21.434627  -0.332169

                                                                  flux_range  \
passband  passband_1 passband_2 passband_3 passband_4 passband_5  passband_0
object_id
615         0.415580   0.339918   0.293128   0.200096   0.125268  242.096031
713        -0.087865  -0.022678  -0.167176  -0.064134   0.218182   29.245007
730         0.471342   2.385066   2.662075   2.537802   1.680352    9.402126
745         7.007099   5.688194   3.751603   3.476420   3.170857   21.888378
1124        2.377222   3.075437   3.603208   3.904008   3.657305   12.135630

                                                                         \
passband    passband_1   passband_2  passband_3  passband_4  passband_5
object_id
615        1761.066406  1293.843445  976.381653  804.138244  801.003235
713          20.844770    20.596960   23.724909   22.114735   28.982050
730           9.086189    23.843549   39.007901   46.996291   66.469870
745         195.862703   222.954965  208.194738  199.127581  151.762677
1124         39.792286   108.756227  142.618675  160.143942  120.018125

          flux_rel_range                                              \
passband      passband_0 passband_1 passband_2 passband_3 passband_4
object_id
615           -74.386845  -4.565898  -9.644999  -8.062373 -14.371264
713           -10.750268 -20.439968 -25.932983 -24.038216 -24.564789
730          -195.550011  64.415192   9.931211  12.053747  10.907231
745            12.176967  34.257340  22.957755  14.445003  15.160726
1124           18.360947   8.585848  10.616611  12.864111  16.166192


passband  passband_5
object_id
615       -16.881050
713       -16.153417
730        14.642890
745        14.122532
1124       17.402149

In [6]:
df_grouped.columns=['flux_min_pb0','flux_min_pb1','flux_min_pb2','flux_min_pb3','flux_min_pb4','flux_min_pb5',
                    'flux_max_pb0','flux_max_pb1','flux_max_pb2','flux_max_pb3','flux_max_pb4','flux_max_pb5',
                    'flux_mean_pb0','flux_mean_pb1','flux_mean_pb2','flux_mean_pb3','flux_mean_pb4','flux_mean_pb5',
                    'flux_std_pb0','flux_std_pb1','flux_std_pb2','flux_std_pb3','flux_std_pb4','flux_std_pb5',
                    'flux_skew_pb0','flux_skew_pb1','flux_skew_pb2','flux_skew_pb3','flux_skew_pb4','flux_skew_pb5',
                    'flux_range_pb0','flux_range_pb1','flux_range_pb2','flux_range_pb3','flux_range_pb4','flux_range_pb5',
                    'flux_relrange_pb0','flux_relrange_pb1','flux_relrange_pb2','flux_relrange_pb3','flux_relrange_pb4','flux_relrange_pb5'
                   ]

In [7]:
df_grouped.head()

,flux_min_pb0,flux_min_pb1,flux_min_pb2,flux_min_pb3,flux_min_pb4,flux_min_pb5,flux_max_pb0,flux_max_pb1,flux_max_pb2,flux_max_pb3,flux_max_pb4,flux_max_pb5,flux_mean_pb0,flux_mean_pb1,flux_mean_pb2,flux_mean_pb3,flux_mean_pb4,flux_mean_pb5,flux_std_pb0,flux_std_pb1,flux_std_pb2,flux_std_pb3,flux_std_pb4,flux_std_pb5,flux_skew_pb0,flux_skew_pb1,flux_skew_pb2,flux_skew_pb3,flux_skew_pb4,flux_skew_pb5,flux_range_pb0,flux_range_pb1,flux_range_pb2,flux_range_pb3,flux_range_pb4,flux_range_pb5,flux_relrange_pb0,flux_relrange_pb1,flux_relrange_pb2,flux_relrange_pb3,flux_relrange_pb4,flux_relrange_pb5
object_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
615,-116.913223,-1100.440063,-681.858887,-530.644592,-422.184509,-422.815094,125.182808,660.626343,611.984558,445.737061,381.953735,378.188141,-3.254554,-385.699911,-134.146566,-121.103501,-55.954592,-47.449847,83.944735,601.787302,455.121346,335.425053,291.803449,294.779522,0.128917,0.415580,0.339918,0.293128,0.200096,0.125268,242.096031,1761.066406,1293.843445,976.381653,804.138244,801.003235,-74.386845,-4.565898,-9.644999,-8.062373,-14.371264,-16.881050
713,-14.735178,-11.715749,-10.067919,-12.394593,-12.286801,-14.211164,14.509829,9.129021,10.529041,11.330316,9.827934,14.770886,-2.720398,-1.019804,-0.794238,-0.986966,-0.900262,-1.794175,7.113509,5.712334,5.770738,6.450413,6.406989,7.094073,0.260052,-0.087865,-0.022678,-0.167176,-0.064134,0.218182,29.245007,20.844770,20.596960,23.724909,22.114735,28.982050,-10.750268,-20.439968,-25.932983,-24.038216,-24.564789,-16.153417
730,-3.459960,-3.393080,-2.848838,-5.435799,-5.836310,-19.159811,5.942166,5.693109,20.994711,33.572102,41.159981,47.310059,-0.048080,0.141057,2.400870,3.236164,4.308728,4.539396,1.828872,1.807229,5.559483,8.191987,10.710344,13.332758,0.356910,0.471342,2.385066,2.662075,2.537802,1.680352,9.402126,9.086189,23.843549,39.007901,46.996291,66.469870,-195.550011,64.415192,9.931211,12.053747,10.907231,14.642890
745,-3.874349,-3.618410,-2.159753,-4.944036,-15.494463,-10.249387,18.014029,192.244293,220.795212,203.250702,183.633118,141.513290,1.797523,5.717394,9.711532,14.412924,13.134436,10.746138,4.374445,25.964659,31.957997,34.967698,33.069053,26.060130,2.023211,7.007099,5.688194,3.751603,3.476420,3.170857,21.888378,195.862703,222.954965,208.194738,199.127581,151.762677,12.176967,34.257340,22.957755,14.445003,15.160726,14.122532
1124,-6.804703,-2.622109,-2.084535,-2.800270,-16.543753,-10.860540,5.330927,37.170177,106.671692,139.818405,143.600189,109.157585,0.660948,4.634637,10.243968,11.086555,9.906102,6.896742,2.360084,8.107525,21.319854,26.270649,26.865913,21.434627,-0.332169,2.377222,3.075437,3.603208,3.904008,3.657305,12.135630,39.792286,108.756227,142.618675,160.143942,120.018125,18.360947,8.585848,10.616611,12.864111,16.166192,17.402149

In [8]:
df_grouped.columns[df_grouped.count() != df_grouped.shape[0]]

Index(['flux_skew_pb0'], dtype='object')

In [9]:
df_grouped[df_grouped.flux_skew_pb0.isnull()]

,flux_min_pb0,flux_min_pb1,flux_min_pb2,flux_min_pb3,flux_min_pb4,flux_min_pb5,flux_max_pb0,flux_max_pb1,flux_max_pb2,flux_max_pb3,flux_max_pb4,flux_max_pb5,flux_mean_pb0,flux_mean_pb1,flux_mean_pb2,flux_mean_pb3,flux_mean_pb4,flux_mean_pb5,flux_std_pb0,flux_std_pb1,flux_std_pb2,flux_std_pb3,flux_std_pb4,flux_std_pb5,flux_skew_pb0,flux_skew_pb1,flux_skew_pb2,flux_skew_pb3,flux_skew_pb4,flux_skew_pb5,flux_range_pb0,flux_range_pb1,flux_range_pb2,flux_range_pb3,flux_range_pb4,flux_range_pb5,flux_relrange_pb0,flux_relrange_pb1,flux_relrange_pb2,flux_relrange_pb3,flux_relrange_pb4,flux_relrange_pb5
object_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
74256178,236.051834,93.445152,22.347017,-21.660635,-14.065358,-34.408787,253.985077,271.138641,275.901489,272.057312,368.689117,522.092834,245.018455,173.985895,158.941465,137.17158,187.849872,250.614106,12.680718,74.748845,84.117696,87.941949,104.56564,162.924219,NaN,0.206658,-0.18979,-0.579486,-0.448251,-0.401889,17.933243,177.693489,253.554472,293.717947,382.754475,556.501621,0.073191,1.02131,1.59527,2.141245,2.037555,2.220552

In [11]:
df_train[(df_train.object_id == 74256178) & (df_train.passband == 'passband_0')]

         object_id         mjd    passband        flux   flux_err  detected
1099109   74256178  59998.1278  passband_0  236.051834  15.632930         1
1099152   74256178  60646.3282  passband_0  253.985077  16.547312         1

In [12]:
df_grouped['flux_skew_pb0'].fillna(0, inplace = True)

In [13]:
df_grouped.columns[df_grouped.count() != df_grouped.shape[0]]

Index([], dtype='object')

In [14]:
df_grouped.to_csv('df_train_FE.csv', index = True, header = True)

In [ ]:
Как преобразовать flux?
Признаки: 
    1) range/mean, max/mean, min/mean - по 6 диапазонам
    2) разница во времени между max и min
    3) сравнения между диапазонами